/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.2.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLineEdit *primary_name;
    QTabWidget *tabWidget;
    QWidget *tab;
    QTabWidget *tabWidget_3;
    QWidget *tab_16;
    QRadioButton *calibration_check_3;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLineEdit *block1;
    QLineEdit *run_3;
    QPushButton *button_movefile_5;
    QLineEdit *subrun3;
    QPushButton *pushButton_4;
    QLineEdit *block2;
    QLabel *label_27;
    QLineEdit *extra_3;
    QLabel *label_28;
    QPushButton *button_save_config_2;
    QWidget *tab_15;
    QLabel *label_7;
    QRadioButton *calibration_check;
    QLabel *triggerCh;
    QLabel *label;
    QLabel *label_4;
    QLabel *label_2;
    QLineEdit *voltage;
    QLineEdit *trigger_channel;
    QLineEdit *run;
    QPushButton *button_movefile;
    QLabel *label_6;
    QLineEdit *subrun;
    QPushButton *pushButton_2;
    QLineEdit *threshold;
    QLabel *label_5;
    QLabel *label_3;
    QLineEdit *extra;
    QPushButton *button_save_config;
    QWidget *tab_2;
    QLineEdit *led_width;
    QLabel *LED_voltage;
    QLineEdit *led_voltage;
    QLabel *width;
    QLabel *label_8;
    QLabel *label_9;
    QPushButton *button_movefile_2;
    QLabel *Information;
    QLineEdit *subrun_2;
    QLabel *label_11;
    QWidget *tab_5;
    QLineEdit *file_type;
    QLabel *file_type_2;
    QCheckBox *enable1;
    QCheckBox *enable2;
    QCheckBox *enable3;
    QCheckBox *enable4;
    QCheckBox *enable5;
    QCheckBox *enable6;
    QCheckBox *enable7;
    QCheckBox *enable8;
    QLabel *label_14;
    QLabel *label_15;
    QCheckBox *trigger1;
    QCheckBox *trigger2;
    QCheckBox *trigger3;
    QCheckBox *trigger4;
    QCheckBox *trigger5;
    QCheckBox *trigger6;
    QCheckBox *trigger7;
    QCheckBox *trigger8;
    QLabel *label_16;
    QCheckBox *externaltrigger;
    QLineEdit *base1;
    QLineEdit *base2;
    QLineEdit *base3;
    QLineEdit *base4;
    QLineEdit *base5;
    QLineEdit *base6;
    QLineEdit *base7;
    QLineEdit *base8;
    QLineEdit *triggerL2;
    QLineEdit *triggerL4;
    QLabel *label_17;
    QLineEdit *triggerL5;
    QLineEdit *triggerL8;
    QLineEdit *triggerL6;
    QLineEdit *triggerL7;
    QLineEdit *triggerL3;
    QLineEdit *triggerL1;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QComboBox *FileTypeSet;
    QPushButton *pushButton_SetConfig;
    QLabel *label_18;
    QLineEdit *time_in_us;
    QLabel *label_19;
    QComboBox *samplingRate;
    QLabel *label_20;
    QComboBox *setPolarity;
    QLabel *file_type_3;
    QSpinBox *usbPort;
    QLabel *label_26;
    QLabel *label_29;
    QLineEdit *postTrigger;
    QComboBox *externalType;
    QLabel *label_30;
    QWidget *tab_3;
    QLabel *label_12;
    QLineEdit *passwrd;
    QLabel *label_13;
    QLineEdit *nwvfs;
    QPushButton *pushButtonRecompile;
    QLabel *Information_2;
    QComboBox *samplingRate_2;
    QLabel *label_21;
    QComboBox *adcMaximumRate;
    QLabel *label_25;
    QLabel *label_10;
    QRadioButton *lock_folder;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QMenuBar *menuBar;
    QMenu *menuLAr_Test;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(509, 518);
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(385, 372));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        primary_name = new QLineEdit(centralWidget);
        primary_name->setObjectName(QString::fromUtf8("primary_name"));
        primary_name->setEnabled(false);
        primary_name->setGeometry(QRect(161, 10, 331, 25));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(primary_name->sizePolicy().hasHeightForWidth());
        primary_name->setSizePolicy(sizePolicy1);
        primary_name->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        primary_name->setReadOnly(false);
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setGeometry(QRect(10, 50, 491, 411));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tabWidget_3 = new QTabWidget(tab);
        tabWidget_3->setObjectName(QString::fromUtf8("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(-8, -1, 501, 371));
        tab_16 = new QWidget();
        tab_16->setObjectName(QString::fromUtf8("tab_16"));
        calibration_check_3 = new QRadioButton(tab_16);
        calibration_check_3->setObjectName(QString::fromUtf8("calibration_check_3"));
        calibration_check_3->setEnabled(false);
        calibration_check_3->setGeometry(QRect(310, 190, 171, 23));
        calibration_check_3->setLayoutDirection(Qt::RightToLeft);
        calibration_check_3->setCheckable(true);
        calibration_check_3->setChecked(true);
        calibration_check_3->setAutoRepeat(false);
        calibration_check_3->setAutoExclusive(false);
        label_22 = new QLabel(tab_16);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(24, 20, 67, 17));
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(tab_16);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 110, 81, 20));
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_24 = new QLabel(tab_16);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(24, 50, 67, 17));
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        block1 = new QLineEdit(tab_16);
        block1->setObjectName(QString::fromUtf8("block1"));
        block1->setGeometry(QRect(94, 80, 371, 21));
        block1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        run_3 = new QLineEdit(tab_16);
        run_3->setObjectName(QString::fromUtf8("run_3"));
        run_3->setGeometry(QRect(94, 20, 91, 21));
        run_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        run_3->setReadOnly(false);
        button_movefile_5 = new QPushButton(tab_16);
        button_movefile_5->setObjectName(QString::fromUtf8("button_movefile_5"));
        button_movefile_5->setGeometry(QRect(380, 40, 89, 25));
        subrun3 = new QLineEdit(tab_16);
        subrun3->setObjectName(QString::fromUtf8("subrun3"));
        subrun3->setGeometry(QRect(94, 50, 91, 21));
        subrun3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButton_4 = new QPushButton(tab_16);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(380, 160, 89, 25));
        QPalette palette;
        QBrush brush(QColor(239, 41, 41, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(255, 51, 51, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        QBrush brush2(QColor(229, 25, 25, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        QBrush brush3(QColor(102, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush3);
        QBrush brush4(QColor(136, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        QBrush brush5(QColor(0, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        QBrush brush6(QColor(229, 127, 127, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        QBrush brush7(QColor(204, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        pushButton_4->setPalette(palette);
        pushButton_4->setAutoFillBackground(false);
        pushButton_4->setStyleSheet(QString::fromUtf8("background-color: rgb(239, 41, 41);\n"
""));
        pushButton_4->setAutoDefault(false);
        pushButton_4->setFlat(false);
        block2 = new QLineEdit(tab_16);
        block2->setObjectName(QString::fromUtf8("block2"));
        block2->setGeometry(QRect(94, 110, 371, 21));
        block2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_27 = new QLabel(tab_16);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(24, 80, 67, 17));
        label_27->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extra_3 = new QLineEdit(tab_16);
        extra_3->setObjectName(QString::fromUtf8("extra_3"));
        extra_3->setGeometry(QRect(90, 140, 201, 21));
        extra_3->setStyleSheet(QString::fromUtf8(""));
        extra_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_28 = new QLabel(tab_16);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 140, 81, 20));
        label_28->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        button_save_config_2 = new QPushButton(tab_16);
        button_save_config_2->setObjectName(QString::fromUtf8("button_save_config_2"));
        button_save_config_2->setGeometry(QRect(310, 290, 161, 25));
        tabWidget_3->addTab(tab_16, QString());
        tab_15 = new QWidget();
        tab_15->setObjectName(QString::fromUtf8("tab_15"));
        label_7 = new QLabel(tab_15);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(16, 180, 81, 20));
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        calibration_check = new QRadioButton(tab_15);
        calibration_check->setObjectName(QString::fromUtf8("calibration_check"));
        calibration_check->setEnabled(false);
        calibration_check->setGeometry(QRect(320, 190, 161, 23));
        calibration_check->setLayoutDirection(Qt::RightToLeft);
        calibration_check->setCheckable(true);
        calibration_check->setChecked(true);
        calibration_check->setAutoRepeat(false);
        calibration_check->setAutoExclusive(false);
        triggerCh = new QLabel(tab_15);
        triggerCh->setObjectName(QString::fromUtf8("triggerCh"));
        triggerCh->setGeometry(QRect(16, 150, 81, 20));
        triggerCh->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label = new QLabel(tab_15);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(30, 30, 67, 17));
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_4 = new QLabel(tab_15);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(16, 120, 81, 20));
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2 = new QLabel(tab_15);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(30, 60, 67, 17));
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        voltage = new QLineEdit(tab_15);
        voltage->setObjectName(QString::fromUtf8("voltage"));
        voltage->setGeometry(QRect(100, 90, 111, 21));
        voltage->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        trigger_channel = new QLineEdit(tab_15);
        trigger_channel->setObjectName(QString::fromUtf8("trigger_channel"));
        trigger_channel->setGeometry(QRect(100, 150, 111, 21));
        trigger_channel->setStyleSheet(QString::fromUtf8(""));
        trigger_channel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        run = new QLineEdit(tab_15);
        run->setObjectName(QString::fromUtf8("run"));
        run->setGeometry(QRect(100, 30, 111, 21));
        run->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        run->setReadOnly(false);
        button_movefile = new QPushButton(tab_15);
        button_movefile->setObjectName(QString::fromUtf8("button_movefile"));
        button_movefile->setGeometry(QRect(380, 40, 89, 25));
        label_6 = new QLabel(tab_15);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(220, 120, 41, 16));
        subrun = new QLineEdit(tab_15);
        subrun->setObjectName(QString::fromUtf8("subrun"));
        subrun->setGeometry(QRect(100, 60, 111, 21));
        subrun->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButton_2 = new QPushButton(tab_15);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(380, 160, 89, 25));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        pushButton_2->setPalette(palette1);
        pushButton_2->setAutoFillBackground(false);
        pushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(239, 41, 41);\n"
""));
        pushButton_2->setAutoDefault(false);
        pushButton_2->setFlat(false);
        threshold = new QLineEdit(tab_15);
        threshold->setObjectName(QString::fromUtf8("threshold"));
        threshold->setGeometry(QRect(100, 120, 111, 21));
        threshold->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_5 = new QLabel(tab_15);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(220, 90, 16, 16));
        label_3 = new QLabel(tab_15);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(30, 90, 67, 17));
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extra = new QLineEdit(tab_15);
        extra->setObjectName(QString::fromUtf8("extra"));
        extra->setGeometry(QRect(100, 180, 111, 21));
        extra->setStyleSheet(QString::fromUtf8(""));
        extra->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        button_save_config = new QPushButton(tab_15);
        button_save_config->setObjectName(QString::fromUtf8("button_save_config"));
        button_save_config->setGeometry(QRect(310, 290, 161, 25));
        tabWidget_3->addTab(tab_15, QString());
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tab_2->setEnabled(false);
        tab_2->setAcceptDrops(false);
        led_width = new QLineEdit(tab_2);
        led_width->setObjectName(QString::fromUtf8("led_width"));
        led_width->setGeometry(QRect(360, 60, 91, 21));
        led_width->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LED_voltage = new QLabel(tab_2);
        LED_voltage->setObjectName(QString::fromUtf8("LED_voltage"));
        LED_voltage->setGeometry(QRect(256, 30, 101, 20));
        LED_voltage->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        led_voltage = new QLineEdit(tab_2);
        led_voltage->setObjectName(QString::fromUtf8("led_voltage"));
        led_voltage->setGeometry(QRect(360, 30, 91, 21));
        led_voltage->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        led_voltage->setReadOnly(false);
        width = new QLabel(tab_2);
        width->setObjectName(QString::fromUtf8("width"));
        width->setGeometry(QRect(266, 60, 91, 20));
        width->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_8 = new QLabel(tab_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(460, 30, 16, 16));
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(460, 60, 16, 16));
        button_movefile_2 = new QPushButton(tab_2);
        button_movefile_2->setObjectName(QString::fromUtf8("button_movefile_2"));
        button_movefile_2->setGeometry(QRect(310, 130, 161, 25));
        Information = new QLabel(tab_2);
        Information->setObjectName(QString::fromUtf8("Information"));
        Information->setGeometry(QRect(10, 20, 201, 201));
        Information->setAutoFillBackground(false);
        Information->setTextFormat(Qt::AutoText);
        Information->setScaledContents(false);
        Information->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        Information->setWordWrap(true);
        subrun_2 = new QLineEdit(tab_2);
        subrun_2->setObjectName(QString::fromUtf8("subrun_2"));
        subrun_2->setGeometry(QRect(360, 90, 91, 21));
        subrun_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_11 = new QLabel(tab_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(290, 90, 67, 17));
        label_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tabWidget->addTab(tab_2, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        file_type = new QLineEdit(tab_5);
        file_type->setObjectName(QString::fromUtf8("file_type"));
        file_type->setEnabled(false);
        file_type->setGeometry(QRect(419, 280, 61, 21));
        file_type->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        file_type->setReadOnly(false);
        file_type_2 = new QLabel(tab_5);
        file_type_2->setObjectName(QString::fromUtf8("file_type_2"));
        file_type_2->setGeometry(QRect(299, 240, 91, 20));
        file_type_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        enable1 = new QCheckBox(tab_5);
        enable1->setObjectName(QString::fromUtf8("enable1"));
        enable1->setGeometry(QRect(0, 50, 61, 27));
        enable1->setLayoutDirection(Qt::RightToLeft);
        enable1->setChecked(true);
        enable2 = new QCheckBox(tab_5);
        enable2->setObjectName(QString::fromUtf8("enable2"));
        enable2->setGeometry(QRect(0, 80, 61, 27));
        enable2->setLayoutDirection(Qt::RightToLeft);
        enable3 = new QCheckBox(tab_5);
        enable3->setObjectName(QString::fromUtf8("enable3"));
        enable3->setGeometry(QRect(0, 110, 61, 27));
        enable3->setLayoutDirection(Qt::RightToLeft);
        enable4 = new QCheckBox(tab_5);
        enable4->setObjectName(QString::fromUtf8("enable4"));
        enable4->setGeometry(QRect(0, 140, 61, 27));
        enable4->setLayoutDirection(Qt::RightToLeft);
        enable5 = new QCheckBox(tab_5);
        enable5->setObjectName(QString::fromUtf8("enable5"));
        enable5->setGeometry(QRect(0, 170, 61, 27));
        enable5->setLayoutDirection(Qt::RightToLeft);
        enable6 = new QCheckBox(tab_5);
        enable6->setObjectName(QString::fromUtf8("enable6"));
        enable6->setGeometry(QRect(0, 200, 61, 27));
        enable6->setLayoutDirection(Qt::RightToLeft);
        enable7 = new QCheckBox(tab_5);
        enable7->setObjectName(QString::fromUtf8("enable7"));
        enable7->setGeometry(QRect(0, 230, 61, 27));
        enable7->setLayoutDirection(Qt::RightToLeft);
        enable8 = new QCheckBox(tab_5);
        enable8->setObjectName(QString::fromUtf8("enable8"));
        enable8->setGeometry(QRect(0, 260, 61, 27));
        enable8->setLayoutDirection(Qt::RightToLeft);
        label_14 = new QLabel(tab_5);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(0, 20, 85, 21));
        label_15 = new QLabel(tab_5);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(60, 20, 85, 21));
        trigger1 = new QCheckBox(tab_5);
        trigger1->setObjectName(QString::fromUtf8("trigger1"));
        trigger1->setEnabled(true);
        trigger1->setGeometry(QRect(80, 50, 61, 27));
        trigger1->setLayoutDirection(Qt::LeftToRight);
        trigger1->setCheckable(true);
        trigger1->setChecked(false);
        trigger1->setTristate(false);
        trigger2 = new QCheckBox(tab_5);
        trigger2->setObjectName(QString::fromUtf8("trigger2"));
        trigger2->setGeometry(QRect(80, 80, 61, 27));
        trigger2->setLayoutDirection(Qt::LeftToRight);
        trigger2->setCheckable(true);
        trigger2->setChecked(false);
        trigger3 = new QCheckBox(tab_5);
        trigger3->setObjectName(QString::fromUtf8("trigger3"));
        trigger3->setGeometry(QRect(80, 110, 61, 27));
        trigger3->setLayoutDirection(Qt::LeftToRight);
        trigger4 = new QCheckBox(tab_5);
        trigger4->setObjectName(QString::fromUtf8("trigger4"));
        trigger4->setGeometry(QRect(80, 140, 61, 27));
        trigger4->setLayoutDirection(Qt::LeftToRight);
        trigger5 = new QCheckBox(tab_5);
        trigger5->setObjectName(QString::fromUtf8("trigger5"));
        trigger5->setGeometry(QRect(80, 170, 61, 27));
        trigger5->setLayoutDirection(Qt::LeftToRight);
        trigger6 = new QCheckBox(tab_5);
        trigger6->setObjectName(QString::fromUtf8("trigger6"));
        trigger6->setGeometry(QRect(80, 200, 61, 27));
        trigger6->setLayoutDirection(Qt::LeftToRight);
        trigger7 = new QCheckBox(tab_5);
        trigger7->setObjectName(QString::fromUtf8("trigger7"));
        trigger7->setGeometry(QRect(80, 230, 61, 27));
        trigger7->setLayoutDirection(Qt::LeftToRight);
        trigger8 = new QCheckBox(tab_5);
        trigger8->setObjectName(QString::fromUtf8("trigger8"));
        trigger8->setGeometry(QRect(80, 260, 61, 27));
        trigger8->setLayoutDirection(Qt::LeftToRight);
        label_16 = new QLabel(tab_5);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(120, 20, 85, 21));
        externaltrigger = new QCheckBox(tab_5);
        externaltrigger->setObjectName(QString::fromUtf8("externaltrigger"));
        externaltrigger->setGeometry(QRect(-10, 340, 161, 27));
        externaltrigger->setLayoutDirection(Qt::RightToLeft);
        base1 = new QLineEdit(tab_5);
        base1->setObjectName(QString::fromUtf8("base1"));
        base1->setGeometry(QRect(120, 51, 41, 20));
        QFont font;
        font.setFamilies({QString::fromUtf8("DejaVu Sans")});
        font.setPointSize(10);
        base1->setFont(font);
        base1->setLayoutDirection(Qt::RightToLeft);
        base1->setAutoFillBackground(false);
        base1->setMaxLength(100);
        base1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base1->setDragEnabled(false);
        base2 = new QLineEdit(tab_5);
        base2->setObjectName(QString::fromUtf8("base2"));
        base2->setGeometry(QRect(120, 80, 41, 20));
        base2->setFont(font);
        base2->setLayoutDirection(Qt::RightToLeft);
        base2->setMaxLength(100);
        base2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base3 = new QLineEdit(tab_5);
        base3->setObjectName(QString::fromUtf8("base3"));
        base3->setGeometry(QRect(120, 110, 41, 20));
        base3->setFont(font);
        base3->setLayoutDirection(Qt::RightToLeft);
        base3->setMaxLength(100);
        base3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base4 = new QLineEdit(tab_5);
        base4->setObjectName(QString::fromUtf8("base4"));
        base4->setGeometry(QRect(120, 140, 41, 20));
        base4->setFont(font);
        base4->setLayoutDirection(Qt::RightToLeft);
        base4->setMaxLength(100);
        base4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base5 = new QLineEdit(tab_5);
        base5->setObjectName(QString::fromUtf8("base5"));
        base5->setGeometry(QRect(120, 170, 41, 20));
        base5->setFont(font);
        base5->setLayoutDirection(Qt::RightToLeft);
        base5->setMaxLength(100);
        base5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base6 = new QLineEdit(tab_5);
        base6->setObjectName(QString::fromUtf8("base6"));
        base6->setGeometry(QRect(120, 200, 41, 20));
        base6->setFont(font);
        base6->setLayoutDirection(Qt::RightToLeft);
        base6->setMaxLength(100);
        base6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base7 = new QLineEdit(tab_5);
        base7->setObjectName(QString::fromUtf8("base7"));
        base7->setGeometry(QRect(120, 230, 41, 20));
        base7->setFont(font);
        base7->setLayoutDirection(Qt::RightToLeft);
        base7->setMaxLength(100);
        base7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        base8 = new QLineEdit(tab_5);
        base8->setObjectName(QString::fromUtf8("base8"));
        base8->setGeometry(QRect(120, 260, 41, 20));
        base8->setFont(font);
        base8->setLayoutDirection(Qt::RightToLeft);
        base8->setMaxLength(100);
        base8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL2 = new QLineEdit(tab_5);
        triggerL2->setObjectName(QString::fromUtf8("triggerL2"));
        triggerL2->setGeometry(QRect(200, 80, 61, 20));
        triggerL2->setFont(font);
        triggerL2->setLayoutDirection(Qt::RightToLeft);
        triggerL2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL4 = new QLineEdit(tab_5);
        triggerL4->setObjectName(QString::fromUtf8("triggerL4"));
        triggerL4->setGeometry(QRect(200, 140, 61, 20));
        triggerL4->setFont(font);
        triggerL4->setLayoutDirection(Qt::RightToLeft);
        triggerL4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_17 = new QLabel(tab_5);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(190, 20, 111, 21));
        triggerL5 = new QLineEdit(tab_5);
        triggerL5->setObjectName(QString::fromUtf8("triggerL5"));
        triggerL5->setGeometry(QRect(200, 170, 61, 20));
        triggerL5->setFont(font);
        triggerL5->setLayoutDirection(Qt::RightToLeft);
        triggerL5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL8 = new QLineEdit(tab_5);
        triggerL8->setObjectName(QString::fromUtf8("triggerL8"));
        triggerL8->setGeometry(QRect(200, 260, 61, 20));
        triggerL8->setFont(font);
        triggerL8->setLayoutDirection(Qt::RightToLeft);
        triggerL8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL6 = new QLineEdit(tab_5);
        triggerL6->setObjectName(QString::fromUtf8("triggerL6"));
        triggerL6->setGeometry(QRect(200, 200, 61, 20));
        triggerL6->setFont(font);
        triggerL6->setLayoutDirection(Qt::RightToLeft);
        triggerL6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL7 = new QLineEdit(tab_5);
        triggerL7->setObjectName(QString::fromUtf8("triggerL7"));
        triggerL7->setGeometry(QRect(200, 230, 61, 20));
        triggerL7->setFont(font);
        triggerL7->setLayoutDirection(Qt::RightToLeft);
        triggerL7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL3 = new QLineEdit(tab_5);
        triggerL3->setObjectName(QString::fromUtf8("triggerL3"));
        triggerL3->setGeometry(QRect(200, 110, 61, 20));
        triggerL3->setFont(font);
        triggerL3->setLayoutDirection(Qt::RightToLeft);
        triggerL3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL1 = new QLineEdit(tab_5);
        triggerL1->setObjectName(QString::fromUtf8("triggerL1"));
        triggerL1->setGeometry(QRect(200, 51, 61, 20));
        triggerL1->setFont(font);
        triggerL1->setLayoutDirection(Qt::RightToLeft);
        triggerL1->setAutoFillBackground(false);
        triggerL1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        triggerL1->setDragEnabled(false);
        line = new QFrame(tab_5);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(100, 50, 20, 231));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(tab_5);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(60, 60, 20, 231));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(tab_5);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(170, 50, 20, 231));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        FileTypeSet = new QComboBox(tab_5);
        FileTypeSet->addItem(QString());
        FileTypeSet->addItem(QString());
        FileTypeSet->setObjectName(QString::fromUtf8("FileTypeSet"));
        FileTypeSet->setGeometry(QRect(399, 240, 81, 29));
        FileTypeSet->setFont(font);
        pushButton_SetConfig = new QPushButton(tab_5);
        pushButton_SetConfig->setObjectName(QString::fromUtf8("pushButton_SetConfig"));
        pushButton_SetConfig->setGeometry(QRect(360, 310, 121, 41));
        QPalette palette2;
        QBrush brush8(QColor(224, 27, 36, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush8);
        QBrush brush9(QColor(255, 112, 118, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush9);
        QBrush brush10(QColor(239, 69, 77, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush10);
        QBrush brush11(QColor(112, 13, 18, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush11);
        QBrush brush12(QColor(149, 18, 24, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush12);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        QBrush brush13(QColor(239, 141, 145, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush13);
        QBrush brush14(QColor(239, 239, 239, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush14);
        QBrush brush15(QColor(255, 255, 255, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush15);
        QBrush brush16(QColor(202, 202, 202, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush16);
        QBrush brush17(QColor(159, 159, 159, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush17);
        QBrush brush18(QColor(184, 184, 184, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush18);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush14);
        QBrush brush19(QColor(118, 118, 118, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush19);
        QBrush brush20(QColor(247, 247, 247, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        QBrush brush21(QColor(177, 177, 177, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush20);
        pushButton_SetConfig->setPalette(palette2);
        label_18 = new QLabel(tab_5);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(339, 20, 161, 21));
        time_in_us = new QLineEdit(tab_5);
        time_in_us->setObjectName(QString::fromUtf8("time_in_us"));
        time_in_us->setGeometry(QRect(389, 50, 61, 20));
        time_in_us->setFont(font);
        time_in_us->setLayoutDirection(Qt::RightToLeft);
        time_in_us->setAutoFillBackground(false);
        time_in_us->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        time_in_us->setDragEnabled(false);
        label_19 = new QLabel(tab_5);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(459, 50, 41, 21));
        samplingRate = new QComboBox(tab_5);
        samplingRate->addItem(QString());
        samplingRate->addItem(QString());
        samplingRate->addItem(QString());
        samplingRate->addItem(QString());
        samplingRate->setObjectName(QString::fromUtf8("samplingRate"));
        samplingRate->setEnabled(false);
        samplingRate->setGeometry(QRect(399, 110, 81, 29));
        label_20 = new QLabel(tab_5);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(369, 80, 161, 21));
        setPolarity = new QComboBox(tab_5);
        setPolarity->addItem(QString());
        setPolarity->addItem(QString());
        setPolarity->setObjectName(QString::fromUtf8("setPolarity"));
        setPolarity->setGeometry(QRect(398, 170, 81, 29));
        setPolarity->setFont(font);
        file_type_3 = new QLabel(tab_5);
        file_type_3->setObjectName(QString::fromUtf8("file_type_3"));
        file_type_3->setGeometry(QRect(270, 170, 121, 20));
        file_type_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        usbPort = new QSpinBox(tab_5);
        usbPort->setObjectName(QString::fromUtf8("usbPort"));
        usbPort->setGeometry(QRect(290, 310, 41, 21));
        label_26 = new QLabel(tab_5);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(210, 310, 91, 21));
        label_29 = new QLabel(tab_5);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(16, 310, 161, 21));
        postTrigger = new QLineEdit(tab_5);
        postTrigger->setObjectName(QString::fromUtf8("postTrigger"));
        postTrigger->setGeometry(QRect(110, 310, 31, 21));
        postTrigger->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        externalType = new QComboBox(tab_5);
        externalType->addItem(QString());
        externalType->addItem(QString());
        externalType->setObjectName(QString::fromUtf8("externalType"));
        externalType->setGeometry(QRect(270, 340, 61, 20));
        externalType->setEditable(true);
        label_30 = new QLabel(tab_5);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(160, 340, 131, 21));
        tabWidget->addTab(tab_5, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        label_12 = new QLabel(tab_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(340, 60, 151, 21));
        label_12->setFont(font);
        label_12->setLayoutDirection(Qt::LeftToRight);
        passwrd = new QLineEdit(tab_3);
        passwrd->setObjectName(QString::fromUtf8("passwrd"));
        passwrd->setGeometry(QRect(340, 240, 113, 29));
        passwrd->setEchoMode(QLineEdit::Password);
        label_13 = new QLabel(tab_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(340, 210, 131, 21));
        label_13->setFont(font);
        nwvfs = new QLineEdit(tab_3);
        nwvfs->setObjectName(QString::fromUtf8("nwvfs"));
        nwvfs->setGeometry(QRect(340, 90, 113, 29));
        pushButtonRecompile = new QPushButton(tab_3);
        pushButtonRecompile->setObjectName(QString::fromUtf8("pushButtonRecompile"));
        pushButtonRecompile->setGeometry(QRect(340, 280, 112, 30));
        pushButtonRecompile->setLayoutDirection(Qt::LeftToRight);
        pushButtonRecompile->setFlat(false);
        Information_2 = new QLabel(tab_3);
        Information_2->setObjectName(QString::fromUtf8("Information_2"));
        Information_2->setGeometry(QRect(10, 40, 301, 251));
        Information_2->setAutoFillBackground(false);
        Information_2->setTextFormat(Qt::AutoText);
        Information_2->setScaledContents(false);
        Information_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        Information_2->setWordWrap(true);
        samplingRate_2 = new QComboBox(tab_3);
        samplingRate_2->addItem(QString());
        samplingRate_2->addItem(QString());
        samplingRate_2->addItem(QString());
        samplingRate_2->addItem(QString());
        samplingRate_2->setObjectName(QString::fromUtf8("samplingRate_2"));
        samplingRate_2->setGeometry(QRect(340, 160, 81, 29));
        label_21 = new QLabel(tab_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(340, 130, 161, 21));
        adcMaximumRate = new QComboBox(tab_3);
        adcMaximumRate->addItem(QString());
        adcMaximumRate->addItem(QString());
        adcMaximumRate->setObjectName(QString::fromUtf8("adcMaximumRate"));
        adcMaximumRate->setGeometry(QRect(200, 280, 81, 29));
        label_25 = new QLabel(tab_3);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 280, 191, 21));
        tabWidget->addTab(tab_3, QString());
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 10, 131, 20));
        label_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lock_folder = new QRadioButton(centralWidget);
        lock_folder->setObjectName(QString::fromUtf8("lock_folder"));
        lock_folder->setEnabled(true);
        lock_folder->setGeometry(QRect(430, 40, 61, 23));
        lock_folder->setCheckable(true);
        lock_folder->setChecked(true);
        lock_folder->setAutoExclusive(false);
        MainWindow->setCentralWidget(centralWidget);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 509, 26));
        menuLAr_Test = new QMenu(menuBar);
        menuLAr_Test->setObjectName(QString::fromUtf8("menuLAr_Test"));
        MainWindow->setMenuBar(menuBar);

        menuBar->addAction(menuLAr_Test->menuAction());

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(0);
        pushButton_4->setDefault(false);
        pushButton_2->setDefault(false);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        primary_name->setText(QCoreApplication::translate("MainWindow", "new_data", nullptr));
        calibration_check_3->setText(QCoreApplication::translate("MainWindow", "Calibration done", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "Run:", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Block2:", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "subrun:", nullptr));
        block1->setText(QString());
        run_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        button_movefile_5->setText(QCoreApplication::translate("MainWindow", "Move files", nullptr));
        subrun3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "Finish run", nullptr));
        block2->setText(QString());
        label_27->setText(QCoreApplication::translate("MainWindow", "Block1:", nullptr));
        extra_3->setText(QString());
        label_28->setText(QCoreApplication::translate("MainWindow", "Extra info:", nullptr));
        button_save_config_2->setText(QCoreApplication::translate("MainWindow", "Save config. file", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_16), QCoreApplication::translate("MainWindow", "Default", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Extra info:", nullptr));
        calibration_check->setText(QCoreApplication::translate("MainWindow", "Calibration done", nullptr));
        triggerCh->setText(QCoreApplication::translate("MainWindow", "Trigger Ch:", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Run:", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Threshold:", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "subrun:", nullptr));
        voltage->setText(QCoreApplication::translate("MainWindow", "42.3", nullptr));
        trigger_channel->setText(QCoreApplication::translate("MainWindow", "Ch0", nullptr));
        run->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        button_movefile->setText(QCoreApplication::translate("MainWindow", "Move files", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "ADC", nullptr));
        subrun->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Finish run", nullptr));
        threshold->setText(QCoreApplication::translate("MainWindow", "20", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "V", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Voltage:", nullptr));
        extra->setText(QString());
        button_save_config->setText(QCoreApplication::translate("MainWindow", "Save config. file", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_15), QCoreApplication::translate("MainWindow", "Style2", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "Acquisition", nullptr));
        led_width->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        LED_voltage->setText(QCoreApplication::translate("MainWindow", "LED Voltage:", nullptr));
        led_voltage->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        width->setText(QCoreApplication::translate("MainWindow", "Width:", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "V", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "ns", nullptr));
        button_movefile_2->setText(QCoreApplication::translate("MainWindow", "Move Calibration files", nullptr));
        Information->setText(QCoreApplication::translate("MainWindow", "If you are running Calibration before data acquisition, make sure that the Acquisition tab have the correct informations", nullptr));
        subrun_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "subrun:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "Calibration", nullptr));
        file_type->setText(QCoreApplication::translate("MainWindow", ".dat", nullptr));
        file_type_2->setText(QCoreApplication::translate("MainWindow", "File type:", nullptr));
        enable1->setText(QCoreApplication::translate("MainWindow", "Ch0", nullptr));
        enable2->setText(QCoreApplication::translate("MainWindow", "Ch1", nullptr));
        enable3->setText(QCoreApplication::translate("MainWindow", "Ch2", nullptr));
        enable4->setText(QCoreApplication::translate("MainWindow", "Ch3", nullptr));
        enable5->setText(QCoreApplication::translate("MainWindow", "Ch4", nullptr));
        enable6->setText(QCoreApplication::translate("MainWindow", "Ch5", nullptr));
        enable7->setText(QCoreApplication::translate("MainWindow", "Ch6", nullptr));
        enable8->setText(QCoreApplication::translate("MainWindow", "Ch7", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Enable", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Trigger", nullptr));
        trigger1->setText(QString());
        trigger2->setText(QString());
        trigger3->setText(QString());
        trigger4->setText(QString());
        trigger5->setText(QString());
        trigger6->setText(QString());
        trigger7->setText(QString());
        trigger8->setText(QString());
#if QT_CONFIG(whatsthis)
        label_16->setWhatsThis(QString());
#endif // QT_CONFIG(whatsthis)
        label_16->setText(QCoreApplication::translate("MainWindow", "Baseline", nullptr));
        externaltrigger->setText(QCoreApplication::translate("MainWindow", "External trigger", nullptr));
        base1->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base2->setInputMask(QString());
        base2->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base3->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base4->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base5->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base6->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base7->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        base8->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL2->setInputMask(QString());
        triggerL2->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL4->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Trigger level", nullptr));
        triggerL5->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL8->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL6->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL7->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL3->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        triggerL1->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        FileTypeSet->setItemText(0, QCoreApplication::translate("MainWindow", "Binary", nullptr));
        FileTypeSet->setItemText(1, QCoreApplication::translate("MainWindow", "ASCII", nullptr));

        pushButton_SetConfig->setText(QCoreApplication::translate("MainWindow", "SET", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Time of acquisition", nullptr));
        time_in_us->setText(QCoreApplication::translate("MainWindow", "20", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "us", nullptr));
        samplingRate->setItemText(0, QCoreApplication::translate("MainWindow", "500 MSamples/s", nullptr));
        samplingRate->setItemText(1, QCoreApplication::translate("MainWindow", "250 MSamples/s", nullptr));
        samplingRate->setItemText(2, QCoreApplication::translate("MainWindow", "125 MSamples/s", nullptr));
        samplingRate->setItemText(3, QCoreApplication::translate("MainWindow", "62.5 MSamples/s", nullptr));

        samplingRate->setCurrentText(QCoreApplication::translate("MainWindow", "500 MSamples/s", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Sampling rate", nullptr));
        setPolarity->setItemText(0, QCoreApplication::translate("MainWindow", "Positive", nullptr));
        setPolarity->setItemText(1, QCoreApplication::translate("MainWindow", "Negative", nullptr));

        file_type_3->setText(QCoreApplication::translate("MainWindow", "Pulse polarity:", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "USB port", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Post trigger:", nullptr));
        postTrigger->setText(QCoreApplication::translate("MainWindow", "50", nullptr));
        externalType->setItemText(0, QCoreApplication::translate("MainWindow", "TTL", nullptr));
        externalType->setItemText(1, QCoreApplication::translate("MainWindow", "NIM", nullptr));

        label_30->setText(QCoreApplication::translate("MainWindow", "External type:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QCoreApplication::translate("MainWindow", "Config.", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "# of waveforms", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "PC password", nullptr));
        pushButtonRecompile->setText(QCoreApplication::translate("MainWindow", "Recompile", nullptr));
        Information_2->setText(QCoreApplication::translate("MainWindow", "This will recompile wavedump setting the number of waveforms you want to save each time you press W (shift+w). \n"
"\n"
"The standard value is 10,000 waveform.\n"
"\n"
"The password is the same you use to login the computer.", nullptr));
        samplingRate_2->setItemText(0, QCoreApplication::translate("MainWindow", "500 MSamples/s", nullptr));
        samplingRate_2->setItemText(1, QCoreApplication::translate("MainWindow", "250 MSamples/s", nullptr));
        samplingRate_2->setItemText(2, QCoreApplication::translate("MainWindow", "125 MSamples/s", nullptr));
        samplingRate_2->setItemText(3, QCoreApplication::translate("MainWindow", "62.5 MSamples/s", nullptr));

        samplingRate_2->setCurrentText(QCoreApplication::translate("MainWindow", "500 MSamples/s", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Sampling rate", nullptr));
        adcMaximumRate->setItemText(0, QCoreApplication::translate("MainWindow", "500 MSamples/s", nullptr));
        adcMaximumRate->setItemText(1, QCoreApplication::translate("MainWindow", "250 MSamples/s", nullptr));

        adcMaximumRate->setCurrentText(QCoreApplication::translate("MainWindow", "500 MSamples/s", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "ADC norminal sampling:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("MainWindow", "Recompile", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Folder name:", nullptr));
        lock_folder->setText(QCoreApplication::translate("MainWindow", "Lock", nullptr));
        menuLAr_Test->setTitle(QCoreApplication::translate("MainWindow", "LAr Test", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
