# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../move_files/move_files/del_dev_channel_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DelDev(object):
    def setupUi(self, DelDev):
        DelDev.setObjectName("DelDev")
        DelDev.resize(381, 71)
        DelDev.setMinimumSize(QtCore.QSize(381, 71))
        DelDev.setMaximumSize(QtCore.QSize(381, 71))
        self.centralwidget = QtWidgets.QWidget(DelDev)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.devname = QtWidgets.QComboBox(self.centralwidget)
        self.devname.setObjectName("devname")
        self.horizontalLayout.addWidget(self.devname)
        self.delb = QtWidgets.QPushButton(self.centralwidget)
        self.delb.setObjectName("delb")
        self.horizontalLayout.addWidget(self.delb)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        DelDev.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DelDev)
        self.statusbar.setObjectName("statusbar")
        DelDev.setStatusBar(self.statusbar)

        self.retranslateUi(DelDev)
        QtCore.QMetaObject.connectSlotsByName(DelDev)

    def retranslateUi(self, DelDev):
        _translate = QtCore.QCoreApplication.translate
        DelDev.setWindowTitle(_translate("DelDev", "Del device"))
        self.label.setText(_translate("DelDev", "Device name"))
        self.delb.setText(_translate("DelDev", "Delete"))
