# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../move_files/move_files/dialog_runlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_RunLog(object):
    def setupUi(self, Dialog_RunLog):
        Dialog_RunLog.setObjectName("Dialog_RunLog")
        Dialog_RunLog.resize(477, 245)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_RunLog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.runlogfield = QtWidgets.QPlainTextEdit(Dialog_RunLog)
        self.runlogfield.setObjectName("runlogfield")
        self.verticalLayout.addWidget(self.runlogfield)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_RunLog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog_RunLog)
        self.buttonBox.accepted.connect(Dialog_RunLog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_RunLog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_RunLog)

    def retranslateUi(self, Dialog_RunLog):
        _translate = QtCore.QCoreApplication.translate
        Dialog_RunLog.setWindowTitle(_translate("Dialog_RunLog", "Insert a run log"))
        self.runlogfield.setPlainText(_translate("Dialog_RunLog", "Keep this line or empty to not save"))
