# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../move_files/move_files/run_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunLog(object):
    def setupUi(self, RunLog):
        RunLog.setObjectName("RunLog")
        RunLog.resize(568, 388)
        self.centralwidget = QtWidgets.QWidget(RunLog)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runlogfield = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.runlogfield.setObjectName("runlogfield")
        self.horizontalLayout.addWidget(self.runlogfield)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.loadb = QtWidgets.QPushButton(self.centralwidget)
        self.loadb.setObjectName("loadb")
        self.horizontalLayout_2.addWidget(self.loadb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.doneb = QtWidgets.QPushButton(self.centralwidget)
        self.doneb.setObjectName("doneb")
        self.horizontalLayout_2.addWidget(self.doneb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        RunLog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RunLog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 24))
        self.menubar.setObjectName("menubar")
        RunLog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RunLog)
        self.statusbar.setObjectName("statusbar")
        RunLog.setStatusBar(self.statusbar)

        self.retranslateUi(RunLog)
        QtCore.QMetaObject.connectSlotsByName(RunLog)

    def retranslateUi(self, RunLog):
        _translate = QtCore.QCoreApplication.translate
        RunLog.setWindowTitle(_translate("RunLog", "Run log"))
        self.runlogfield.setPlainText(_translate("RunLog", "Keep this line or empty to not save"))
        self.loadb.setText(_translate("RunLog", "Load"))
        self.doneb.setText(_translate("RunLog", "Done"))
